#!/bin/bash

CMDNAME=`basename $0`
OUTFILE=$2_https_tracecheck_$1.txt
TARGET=/tracetest.html

if [ $# -ne 2 ]; then
        echo "Usage: $CMDNAME ip port" 1>&2
        exit 1
fi

HDR1="User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
HDR2="Connection: close"

echo -e "# curl -ik -X TRACE https://$1:$2/tracetest.html" > $OUTFILE 2>&1
curl -iks -X TRACE https://$1:$2/tracetest.html >> $OUTFILE 2>&1

# echo -e "********* TRACE $TARGET HTTP/1.0 ********" > $OUTFILE 2>&1
#echo -e "# curl -i -X TRACE https://$1:$2/tracetest.html


#echo -e "\r\n\r\n********* TRACE $TARGET HTTP/1.1 ********" >> $OUTFILE 2>&1
#echo -e "# openssl s_client -quiet -connect $1:$2 2>/dev/null\r\nTRACE $TARGET HTTP/1.1\r\nHost: $1\r\n$HDR1\r\n$HDR2\r\n\r\n" >> $OUTFILE 2>&1
#echo -e "TRACE $TARGET HTTP/1.1\r\nHost: $1\r\n$HDR1\r\n$HDR2\r\n\r\n" | openssl s_client -quiet -connect $1:$2 2>/dev/null>> $OUTFILE 
