#!/bin/bash

CMDNAME=`basename $0`
OUTFILE=$2_https_expect_$1.txt

if [ $# -ne 2 ]; then
        echo "Usage: $CMDNAME ip port" 1>&2
        exit 1
fi

HEADER1="Accept: text/html, application/xhtml+xml, */*"
HEADER2="Accept-Language: ja-JP"
HEADER3="User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
HEADER4="Accept-Encoding: gzip, deflate"
HEADER5="Connection: close"


#echo -e "\r\n\r\n********* Expect Header  ********" >> $OUTFILE 2>&1
#echo -e "# openssl s_client -quiet -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n\r\n" >> $OUTFILE 2>&1
#echo -e "GET / HTTP/1.1\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1
#echo -e "\r\n" >> $OUTFILE 2>&1
curl -iks -H "Expect: <script>alert(1);</script>" https://$1:$2/ >> $OUTFILE 2>&1
exit 0
