#!/bin/bash

CMDNAME=`basename $0`
OUTFILE=$2_https_basecheck_$1.txt

if [ $# -ne 2 ]; then
        echo "Usage: $CMDNAME ip port" 1>&2
        exit 1
fi

HEADER1="Accept: text/html, application/xhtml+xml, */*"
HEADER2="Accept-Language: ja-JP"
HEADER3="User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
HEADER4="Accept-Encoding: gzip, deflate"
HEADER5="Connection: close"

echo -e "******** HEAD / HTTP/1.0 ********" > $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nHEAD / HTTP/1.0\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "HEAD / HTTP/1.0\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n******** HEAD / HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nHEAD / HTTP/1.1\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "HEAD / HTTP/1.1\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n******** GET / HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
curl -isk https://$1:$2/ >> $OUTFILE

echo -e "\r\n******** GET /~root HTTP/1.0 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET /~root HTTP/1.0\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET /~root HTTP/1.0\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n******** GET /~root HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET /~root HTTP/1.1\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET /~root HTTP/1.1\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* TRACE / HTTP/1.0 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nTRACE / HTTP/1.0\r\n\r\n" >> $OUTFILE 2>&1
echo -e "TRACE / HTTP/1.0\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* TRACE / HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nTRACE / HTTP/1.1\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "TRACE / HTTP/1.1\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* OPTIONS / HTTP/1.0 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nOPTIONS / HTTP/1.0\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "OPTIONS / HTTP/1.0\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* OPTIONS / HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nOPTIONS / HTTP/1.1\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "OPTIONS / HTTP/1.1\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* OPTIONS * HTTP/1.0 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nOPTIONS * HTTP/1.0\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "OPTIONS * HTTP/1.0\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | timeout 3 openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* OPTIONS * HTTP/1.1 ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nOPTIONS * HTTP/1.1\r\nHost: $1\r\n\r\n" >> $OUTFILE 2>&1
echo -e "OPTIONS * HTTP/1.1\r\nHost: $1\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\n\r\n" | timeout 3 openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* Range Header DoS Check1(Range header) ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\nRange: bytes=-1, 0-5\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.1\r\nHost: $1\r\nRange: bytes=-1, 0-5\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n"  | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* Range Header DoS Check2(Request-range header) ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\nRequest-range: bytes=-1, 0-5\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.1\r\nHost: $1\r\nRequest-range: bytes=-1, 0-5\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n"  | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* Range Header DoS Check3(Range header 6 bytes ranges) ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\nRange: bytes=0-1, 0-2, 0-3, 1-2, 1-3, 2-3\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.1\r\nHost: $1\r\nRange: bytes=0-1, 0-2, 0-3, 1-2, 1-3, 2-3\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n"  | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* Range Header DoS Check4(Request-range header 6 bytes ranges) ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\nRequest-range: bytes=0-1, 0-2, 0-3, 1-2, 1-3, 2-3\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.1\r\nHost: $1\r\nRequest-range: bytes=0-1, 0-2, 0-3, 1-2, 1-3, 2-3\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n"  | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* Expect Header  ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\nGET / HTTP/1.1\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.1\r\nHost: $1\r\nExpect: <script>alert(1);</script>\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* XSS in Method  ********" >> $OUTFILE 2>&1
echo -e "openssl s_client -quiet -connect $1:$2\r\n<script>alert(1)</script> / HTTP/1.1\r\nHost: $1\r\nContent-Length: 0\r\nContent-Length: 0\r\nContent-Length: 0\r\n\r\n" >> $OUTFILE 2>&1
echo -e "<script>alert(1)</script> / HTTP/1.1\r\nHost: $1\r\nContent-Length: 0\r\nContent-Length: 0\r\nContent-Length: 0\r\n\r\n" | openssl s_client -quiet -connect $1:$2 >> $OUTFILE 2>&1

echo -e "\r\n\r\n********* Apache Verison Check *********">>$OUTFILE 2>&1
echo -e "openssl s_client -quiet $1:$2\r\nGET / HTTP/1.0\r\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|before2_2_21\r\n" >> $OUTFILE 2>&1
echo -e "GET / HTTP/1.0\r\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|before2_2_21\r\n$HEADER1\r\n$HEADER2\r\n$HEADER3\r\n$HEADER4\r\n$HEADER5\r\n\r\n"|openssl s_client -quiet -connect $1:$2 >>$OUTFILE 2>&1

echo -e "\r\n\r\n******** CRLF Injection Check ********" >> $OUTFILE 2>&1
echo -e "curl -ik https://$1:$2/test%0a%0a%0d%0d<s>test</s>12345678" >> $OUTFILE 2>&1
curl -ik https://$1:$2/test%0a%0a%0d%0d<s>test</s>12345678 >> $OUTFILE 2>&1

echo "  **** HTTP check completed. ****"
exit 0
