#!/bin/bash

CMDNAME=`basename $0`
OUTFILE=$2_sslocsp_$1.txt
STARTTLS="$3 $4"
TIMEOUT=3

cp /dev/null $OUTFILE

# 引数が4つまたは2つ以外のとき、エラーメッセージを表示して終了
if [ $# -ne 4 ] && [ $# -ne 2 ]; then
        echo -e "\r\\n#### Error ####\r\n\rCommand usage: $CMDNAME ipaddress port (-starttls pop3|smtp|imap|ftp) " 1>&2
        exit 1
fi

# 引数が2つのとき、starttlsで接続しないopenssl接続
# COMMAND変数にopensslコマンドを挿入
if [ $# = 2 ]; then
        COMMAND="openssl s_client -connect $1:$2 -servername $1"
fi

# 引数が4つのとき、starttlsで接続
if [ $# = 4 ]; then
        COMMAND="openssl s_client $STARTTLS -connect $1:$2 -servername $1"
        if [ "$STARTTLS" != "-starttls pop3" ] && [ "$STARTTLS" != "-starttls smtp" ] && [ "$STARTTLS" != "-starttls imap" ] && [ "$STARTTLS" != "-starttls ftp" ]; then
                echo "Usage: $CMDNAME ip port -starttls pop3|smtp|imap|ftp #2" 1>&2
                exit 1
        fi
fi

CERTINFO=`$COMMAND < /dev/null 2>/dev/null | openssl x509 -text -noout`
OCSPRESPONSE=`$COMMAND -status < /dev/null 2> /dev/null`

if echo "$CERTINFO" | grep OCSP  > /dev/null; then
	if echo "$OCSPRESPONSE" | grep "OCSP Response Status: successful" > /dev/null; then
		echo "---- NOT VULNERABLE (OCSP Staplint is supported.) ----" >> $OUTFILE
		echo "$CERTINFO" | grep "OCSP - URI" >> $OUTFILE
		NUM=`echo "$OCSPRESPONSE" | grep -n "======================================"  | sed -n '2p' |sed 's/:.*//g'`
		echo "$OCSPRESPONSE" | sed -n 1,"$NUM"p >> $OUTFILE
	else
#		echo "---- VULNERABLE ----" >> $OUTFILE
		echo "# $COMMAND < /dev/null 2>/dev/null| openssl x509 -text -noout | grep \"OCSP - URI\"" >> $OUTFILE
		echo "$CERTINFO" | grep "OCSP - URI" | sed 's/^ *//g' >> $OUTFILE
		echo "" >> $OUTFILE
		echo "# $COMMAND -status < /dev/null 2> /dev/null" >> $OUTFILE
		echo "$OCSPRESPONSE" | sed -n "1,3p" >>  $OUTFILE
		echo "～ 省略 ～" >>  $OUTFILE
	fi
else
	echo "---- NOT VULNERABLE (OCSP is NOT supported.) ----" >> $OUTFILE
fi

exit
