#!/bin/bash
nmap -n -sTV -O -Pn -r -v -p -10000 -oN nmap_tcp_10000.txt $1
nmap -n -sTV -O -Pn -r -v -p 10001-20000 -oN nmap_tcp_20000.txt $1
nmap -n -sTV -O -Pn -r -v -p 20001-30000 -oN nmap_tcp_30000.txt $1
nmap -n -sTV -O -Pn -r -v -p 30001-40000 -oN nmap_tcp_40000.txt $1
nmap -n -sTV -O -Pn -r -v -p 40001-50000 -oN nmap_tcp_50000.txt $1
nmap -n -sTV -O -Pn -r -v -p 50001-60000 -oN nmap_tcp_60000.txt $1
nmap -n -sTV -O -Pn -r -v -p 60001- -oN nmap_tcp_65535.txt $1
 
